# Generated by Django 5.0.4 on 2024-04-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimPeriodo',
            fields=[
                ('PeriodoKey', models.IntegerField(primary_key=True, serialize=False)),
                ('Periodo', models.CharField(max_length=8)),
                ('Fecha', models.DateField()),
                ('Anio', models.IntegerField()),
                ('Semestre', models.CharField(max_length=30)),
                ('Trimestre', models.CharField(max_length=30)),
                ('Mes', models.CharField(max_length=20)),
                ('Dia', models.IntegerField()),
                ('NroMes', models.IntegerField()),
            ],
        ),
    ]
