# Generated by Django 5.0.4 on 2024-04-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dimperiodo',
            table='DimPeriodo',
        ),
    ]
