# Generated by Django 5.0.4 on 2024-04-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_dimperiodo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAESTRO_HIS_ESTABLECIMIENTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Establecimiento', models.IntegerField()),
                ('Nombre_Establecimiento', models.CharField(max_length=100)),
                ('Ubigueo_Establecimiento', models.CharField(max_length=6)),
                ('Codigo_Disa', models.IntegerField()),
                ('Disa', models.CharField(max_length=80)),
                ('Codigo_Red', models.CharField(max_length=2)),
                ('Red', models.CharField(max_length=70)),
                ('Codigo_MicroRed', models.CharField(max_length=2)),
                ('MicroRed', models.CharField(max_length=70)),
                ('Codigo_Unico', models.CharField(max_length=9)),
                ('Codigo_Sector', models.IntegerField()),
                ('Descripcion_Sector', models.CharField(max_length=50)),
                ('Departamento', models.CharField(max_length=150)),
                ('Provincia', models.CharField(max_length=150)),
                ('Distrito', models.CharField(max_length=150)),
                ('Categoria_Establecimiento', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'MAESTRO_HIS_ESTABLECIMIENTO',
            },
        ),
    ]
