# Generated by Django 5.0.4 on 2024-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimDisFisicaCie',
            fields=[
                ('CieKey', models.IntegerField(primary_key=True, serialize=False)),
                ('Cie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DimDisFisicaCie',
            },
        ),
    ]
