# Generated by Django 5.0.4 on 2024-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0002_dimdisfisicacie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimdisfisicacie',
            name='Cie',
            field=models.CharField(max_length=100),
        ),
    ]
