# Generated by Django 5.0.4 on 2024-05-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0003_alter_dimdisfisicacie_cie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramaBaseDiscapacidadRpt01CapacitacionMedicinaNominal',
            fields=[
                ('id_cita', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('renaes', models.CharField(max_length=9)),
                ('id_persona', models.CharField(max_length=50, null=True)),
                ('periodo', models.CharField(max_length=8, null=True)),
                ('fichafam', models.CharField(max_length=50, null=True)),
                ('ubigeo', models.IntegerField(null=True)),
                ('edad', models.IntegerField(null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('et', models.CharField(max_length=2, null=True)),
                ('fi', models.CharField(max_length=2, null=True)),
                ('id_profesional', models.CharField(max_length=50, null=True)),
                ('Categoria', models.IntegerField(null=True)),
                ('gedad', models.IntegerField(null=True)),
                ('casos', models.IntegerField(null=True)),
                ('pais', models.CharField(max_length=3, null=True)),
                ('id_ups', models.CharField(max_length=6, null=True)),
            ],
            options={
                'db_table': 'TRAMA_BASE_DISCAPACIDAD_RPT_01_CAPACITACION_MEDICINA_NOMINAL',
            },
        ),
        migrations.CreateModel(
            name='TramaBaseDiscapacidadRpt03SensorialNominal',
            fields=[
                ('id_cita', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('renaes', models.CharField(max_length=9)),
                ('id_persona', models.CharField(max_length=50, null=True)),
                ('periodo', models.CharField(max_length=8, null=True)),
                ('fichafam', models.CharField(max_length=50, null=True)),
                ('ubigeo', models.IntegerField(null=True)),
                ('edad', models.IntegerField(null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('et', models.CharField(max_length=2, null=True)),
                ('fi', models.CharField(max_length=2, null=True)),
                ('id_profesional', models.CharField(max_length=50, null=True)),
                ('Categoria', models.IntegerField(null=True)),
                ('gedad', models.IntegerField(null=True)),
                ('pais', models.CharField(max_length=3, null=True)),
                ('id_ups', models.CharField(max_length=6, null=True)),
            ],
            options={
                'db_table': 'TRAMA_BASE_DISCAPACIDAD_RPT_03_SENSORIAL_NOMINAL',
            },
        ),
        migrations.CreateModel(
            name='TramaBaseDiscapacidadRpt04CertificadoNominal',
            fields=[
                ('id_cita', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('renaes', models.CharField(max_length=9)),
                ('id_persona', models.CharField(max_length=50, null=True)),
                ('periodo', models.CharField(max_length=8, null=True)),
                ('fichafam', models.CharField(max_length=50, null=True)),
                ('ubigeo', models.IntegerField(null=True)),
                ('edad', models.IntegerField(null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('et', models.CharField(max_length=2, null=True)),
                ('fi', models.CharField(max_length=2, null=True)),
                ('id_profesional', models.CharField(max_length=50, null=True)),
                ('Categoria', models.IntegerField(null=True)),
                ('gedad', models.IntegerField(null=True)),
                ('pais', models.CharField(max_length=3, null=True)),
                ('id_ups', models.CharField(max_length=6, null=True)),
            ],
            options={
                'db_table': 'TRAMA_BASE_DISCAPACIDAD_RPT_04_CERTIFICADO_NOMINAL',
            },
        ),
        migrations.CreateModel(
            name='TramaBaseDiscapacidadRpt05RBCNominal',
            fields=[
                ('id_cita', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('renaes', models.CharField(max_length=9)),
                ('id_persona', models.CharField(max_length=50, null=True)),
                ('periodo', models.CharField(max_length=8, null=True)),
                ('fichafam', models.CharField(max_length=50, null=True)),
                ('ubigeo', models.IntegerField(null=True)),
                ('edad', models.IntegerField(null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('et', models.CharField(max_length=2, null=True)),
                ('fi', models.CharField(max_length=2, null=True)),
                ('id_profesional', models.CharField(max_length=50, null=True)),
                ('Categoria', models.IntegerField(null=True)),
                ('gedad', models.IntegerField(null=True)),
                ('pais', models.CharField(max_length=3, null=True)),
                ('id_ups', models.CharField(max_length=6, null=True)),
            ],
            options={
                'db_table': 'TRAMA_BASE_DISCAPACIDAD_RPT_05_RBC_NOMINAL',
            },
        ),
        migrations.CreateModel(
            name='TramaBaseDiscapacidadRpt06CapacitacionAgenteNominal',
            fields=[
                ('id_cita', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('renaes', models.CharField(max_length=9)),
                ('id_persona', models.CharField(max_length=50, null=True)),
                ('periodo', models.CharField(max_length=8, null=True)),
                ('fichafam', models.CharField(max_length=50, null=True)),
                ('ubigeo', models.IntegerField(null=True)),
                ('edad', models.IntegerField(null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('et', models.CharField(max_length=2, null=True)),
                ('fi', models.CharField(max_length=2, null=True)),
                ('id_profesional', models.CharField(max_length=50, null=True)),
                ('Categoria', models.IntegerField(null=True)),
                ('gedad', models.IntegerField(null=True)),
                ('pais', models.CharField(max_length=3, null=True)),
                ('id_ups', models.CharField(max_length=6, null=True)),
            ],
            options={
                'db_table': 'TRAMA_BASE_DISCAPACIDAD_RPT_06_CAPACITACION_AGENTE_NOMINAL',
            },
        ),
    ]
