# Generated by Django 5.0.4 on 2024-05-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0004_tramabasediscapacidadrpt01capacitacionmedicinanominal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramabasediscapacidadrpt05rbcnominal',
            name='casos',
            field=models.IntegerField(null=True),
        ),
    ]
