# Generated by Django 5.0.4 on 2024-08-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0008_directorio_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorio_municipio',
            name='req_resolucion',
            field=models.FileField(blank=True, null=True, upload_to='discapacidad/static/resolucion'),
        ),
    ]
