# Generated by Django 5.0.4 on 2024-08-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0009_alter_directorio_municipio_req_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorio_municipio',
            name='estado_usuario',
            field=models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Continuador', 'Continuador'), ('Espera respuesta MINSA', 'Espera respuesta MINSA')], max_length=100, null=True),
        ),
    ]
