# Generated by Django 5.0.4 on 2024-08-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0010_alter_directorio_municipio_estado_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorio_municipio',
            name='situacion_usuario',
            field=models.CharField(blank=True, choices=[('No llega el correo con la contraseña temporal', 'No llega el correo con la contraseña temporal'), ('Usuario aparece bloqueado', 'Usuario aparece bloqueado'), ('Solicitud de ALTA TEMPORAL', 'Solicitud de ALTA TEMPORAL'), ('Solicitud de USUARIO NUEVO', 'Solicitud de USUARIO NUEVO'), ('Distrito asignado no corresponde', 'Distrito asignado no corresponde'), ('Usuario no pertenece a un grupo válido', 'Usuario no pertenece a un grupo válido'), ('Otros', 'Otros')], max_length=100, null=True),
        ),
    ]
