# Generated by Django 5.0.4 on 2024-08-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0011_alter_directorio_municipio_situacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorio_municipio',
            name='cargo',
            field=models.CharField(blank=True, choices=[('1', 'Responsable PN'), ('2', 'Responsable SELLO'), ('3', 'Responsable COMPROMISO 1'), ('4', 'Gerente desarrollo social'), ('5', 'Consulta Municipio')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directorio_municipio',
            name='situacion_usuario',
            field=models.CharField(blank=True, choices=[('Tengo Usuario', 'Tengo Usuario'), ('No llega el correo con la contraseña temporal', 'No llega el correo con la contraseña temporal'), ('Usuario aparece bloqueado', 'Usuario aparece bloqueado'), ('Solicitud de ALTA TEMPORAL', 'Solicitud de ALTA TEMPORAL'), ('Solicitud de USUARIO NUEVO', 'Solicitud de USUARIO NUEVO'), ('Distrito asignado no corresponde', 'Distrito asignado no corresponde'), ('Usuario no pertenece a un grupo válido', 'Usuario no pertenece a un grupo válido'), ('Otros', 'Otros')], max_length=100, null=True),
        ),
    ]
