# Generated by Django 5.0.4 on 2024-08-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0012_alter_directorio_municipio_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorio_municipio',
            name='estado_auditoria',
            field=models.CharField(blank=True, choices=[('0', 'Pendiente'), ('1', 'Aprobado'), ('2', 'Proceso'), ('3', 'Observado')], max_length=50, null=True),
        ),
    ]
