# Generated by Django 5.0.4 on 2024-08-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0013_alter_directorio_municipio_estado_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(blank=True, max_length=100, null=True)),
                ('hora', models.CharField(blank=True, max_length=100, null=True)),
                ('Descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
