# Generated by Django 5.0.4 on 2024-08-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0015_alter_actualizacion_fecha_alter_actualizacion_hora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actualizacion',
        ),
    ]
