# Generated by Django 5.0.4 on 2024-08-21 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discapacidad', '0016_delete_actualizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio_salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('Carnet de Extranjeria', 'Carnet de Extranjeria'), ('Pasaporte', 'Pasaporte'), ('Cedula de Identidad', 'Cedula de Identidad'), ('Carnet de solicitante de refugio', 'Carnet de solicitante de refugio'), ('Sin Documento', 'Sin Documento')], max_length=100, null=True)),
                ('documento_identidad', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=200, null=True)),
                ('nombres', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=200, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('ubigueo', models.CharField(blank=True, max_length=100, null=True)),
                ('red', models.CharField(blank=True, max_length=100, null=True)),
                ('microred', models.CharField(blank=True, max_length=100, null=True)),
                ('establecimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, choices=[('1', 'Responsable PN'), ('2', 'Responsable PROMSA'), ('3', 'Responsable IMNUMIZACIONES'), ('4', 'Otros')], max_length=100, null=True)),
                ('perfil', models.CharField(blank=True, choices=[('1', 'Consultor'), ('2', 'Registrador')], max_length=100, null=True)),
                ('condicion', models.CharField(blank=True, choices=[('1', 'Alta'), ('0', 'Baja')], max_length=100, null=True)),
                ('cuenta_usuario', models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Si'), ('3', 'Espera respuesta MINSA/RENIEC')], max_length=100, null=True)),
                ('estado_usuario', models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Continuador', 'Continuador'), ('Espera respuesta MINSA', 'Espera respuesta MINSA')], max_length=100, null=True)),
                ('situacion_usuario', models.CharField(blank=True, choices=[('Tengo Usuario', 'Tengo Usuario'), ('No llega el correo con la contraseña temporal', 'No llega el correo con la contraseña temporal'), ('Usuario aparece bloqueado', 'Usuario aparece bloqueado'), ('Solicitud de ALTA TEMPORAL', 'Solicitud de ALTA TEMPORAL'), ('Solicitud de USUARIO NUEVO', 'Solicitud de USUARIO NUEVO'), ('Distrito asignado no corresponde', 'Distrito asignado no corresponde'), ('Usuario no pertenece a un grupo válido', 'Usuario no pertenece a un grupo válido'), ('Otros', 'Otros')], max_length=100, null=True)),
                ('condicion_laboral', models.CharField(blank=True, choices=[('Nombrado', 'Nombrado'), ('Contrato Plazo Fijo', 'Contrato Plazo Fijo'), ('Contrato Plazo Indet.', 'Contrato Plazo Indet.'), ('Contrato-CAS', 'Contrato-CAS'), ('Destacado Externo', 'Destacado Externo'), ('Contrato P.S./CAS Asistencial', 'Contrato P.S./CAS Asistencial'), ('Tercero', 'Tercero')], max_length=200, null=True)),
                ('estado_auditoria', models.CharField(blank=True, choices=[('0', 'Pendiente'), ('1', 'Aprobado'), ('2', 'Proceso'), ('3', 'Observado')], max_length=50, null=True)),
                ('req_oficio', models.FileField(blank=True, null=True, upload_to='discapacidad/static/oficio')),
                ('dateTimeOfUpload_req_oficio', models.DateTimeField(auto_now=True, null=True)),
                ('req_resolucion', models.FileField(blank=True, null=True, upload_to='discapacidad/static/resolucion')),
                ('dateTimeOfUpload_req_resolucion', models.DateTimeField(auto_now=True, null=True)),
                ('req_formato_alta', models.FileField(blank=True, null=True, upload_to='discapacidad/static/formato_alta')),
                ('dateTimeOfUpload_req_formato_alta', models.DateTimeField(auto_now=True, null=True)),
                ('req_formato_excel', models.FileField(blank=True, null=True, upload_to='discapacidad/static/formato_excel')),
                ('dateTimeOfUpload_req_formato_excel', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
